config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts, controllers: { omniauth_callbacks: "accounts/omniauth_callbacks", registrations: 'accounts/registrations' }
  
  resources "conversations" do 
    resources "messages"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get "/browse" => "browse#browse", as: :browse
  get "/matches" => "browse#matches", as: :matches
  post "/approve/:id" => "browse#approve", as: :approve_user
  post "/decline/:id" => "browse#decline", as: :decline_user
  post "get/conversation/:id" => "browse#open_conversation", as: :open_conversation
  post "get/profile_show/:id" => "browse#profile_show", as: :profile_show
  
  
  
  root to:'public#home'
end

app/views/layouts/_footer.html.erb
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <small class="d-block mb-3 text-white" style="text-align: center; font-size: 18px; font-family: Lucida Console, Courier New, monospace;">MyTinder by Žak Lubej Šolski center Velenje ERŠ 2022</small>
      </div>
    </div>
  </footer>

app/views/layouts/_nav.html.erb
<div class="d-flex flex-column flex-md-row align-items-center pb-3 shadow-sm">
      <%= link_to image_pack_tag('tinder_icon.png', class: 'logo-navbar'), root_path %>
      <h5 class="my-0 mr-md-auto font-weight-normal" style="font-size: 30px; font-family: Verdana;">MyTinder</h5>

      <% if account_signed_in? %>

        <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
          <%= link_to "Browse", browse_path, class: "me-3 py-2 text-dark text-decoration-none" %>
          <%= link_to "My Matches", matches_path, class: "me-3 py-2 text-dark text-decoration-none" %>
          <%= link_to "Settings", edit_account_registration_path, class: "me-3 py-2 text-dark text-decoration-none" %>
        </nav>

        <%= link_to "Sign out", destroy_account_session_path, method: :delete, class: "btn btn-secondary me-2" %>

        <% else %>
          <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
          </nav>

        <%= link_to "Sign in", new_account_session_path, class: "w-25 btn btn-secondary me-2", style:"font-weight: bold;"%>
        <%= link_to "Sign up", new_account_registration_path, class: "w-15 btn btn-outline-primary me-3", style:"" %>

      <% end %>
</div>
  

app/views/layouts/_profile_bar.html.erb
<div class="bg-danger profile-bar"> 
        
        
    <%= link_to "Sign Out ", destroy_account_session_path, method: :delete ,class: "sign_out text-white", style:""%> 
    
    <%= link_to(edit_account_registration_path, style:"color: #fd267d;") do %>
        <% if current_account.image.attached? %>
                    <%= image_tag(current_account.image, width: "40px", height: "40px", class: "float-left profile-thumb rounded-circle mr-3") %>
                    <% elsif current_account.image_social? %>
                        <%= image_tag(current_account.image_social, width: "40px", height: "40px", class: "float-left profile-thumb rounded-circle mr-3") %>
                    <% else %>
                        <%= image_pack_tag('default-profile.png', width: "40px", height: "40px", class: "float-left profile-thumb rounded-circle mr-3") %>
        <% end %>
    <% end %>
    
    <%= link_to "My Profile ", edit_account_registration_path ,class: "my-profile text-white", style:""%> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyTinder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>

    <%= favicon_link_tag asset_path('tinder_icon.png') %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous" />

  </head>

  <body style="background: linear-gradient(262deg, #ff7854, #fd267d);">
    <%= render "layouts/nav" unless account_signed_in?%>

    <div class="container-fluid p-0" style="min-height: 100vh; overflow-x: hidden;">
      <%= yield %>
    </div>

    <%= render "layouts/footer" unless account_signed_in?%>
  </body>
</html>